version: "3"
services:
  echo:
    image: gcr.io/hello-minikube-zero-install/hello-node
    ports:
      - "8080:8080"

  flogger:
    image: mingrammer/flog
    command: flog --loop --delay 1 -f rfc5424
